### ISSUE TITLE
Unable to generate documentation

### ISSUE THREAD

**Issue by deep-programmer** [ethz-asl/kindr#101]
Following the instructions given under heading ****Building the documentation**** in the project main page, and executing given commands in the project directory ( `${PROJECT_SOURCE_DIR}` ), after the last step `make doc`, no documentation appears to be generated at the location specified i.e. no `index.html` can be found in `${PROJECT_SOURCE_DIR}/doc/doxygen/doc/html/` [currently](https://github.com/ethz-asl/kindr/commit/12f1fc5250ef28ce35f56e31a356f67b1c637b11). I am using CMake ver. 3.5.1 and Doxygen ver. 1.8.11 on Ubuntu 16.04 ( 64-bit ).

Please help me generate the documentation.

**Comment by remod** [comment]
Thanks for the catch. I fixed the outdated documentation with https://github.com/ethz-asl/kindr/pull/102
