### ISSUE TITLE
How do i install this on ros-kinetic?

### ISSUE THREAD

**Issue by chrissunny94** [ethz-asl/kindr#104]

**Comment by marco-tranzatto** [comment]
Hi, I suggest you start from [building-with-catkin](https://github.com/ethz-asl/kindr#building-with-catkin) and use the instructions in the section "catkin command line tools:".

Regards,
Marco.

**Comment by chrissunny94** [comment]
Thanks , its solved , i had issues with referencing kindr package , i put it in the same src folder and it fixed it .

Thanks anyways
