### ISSUE TITLE
`Building unit tests with gtest` step does not work

### ISSUE THREAD

**Issue by jwdinius** [ethz-asl/kindr#107]
When executing `wget http://googletest.googlecode.com/files/gtest-1.7.0.zip` a "404 not found" error is thrown

> --2018-06-23 09:33:43--  http://googletest.googlecode.com/files/gtest-1.7.0.zip
Resolving googletest.googlecode.com (googletest.googlecode.com)... 74.125.28.82, 2607:f8b0:400e:c08::52
Connecting to googletest.googlecode.com (googletest.googlecode.com)|74.125.28.82|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-06-23 09:33:43 ERROR 404: Not Found.

**Comment by remod** [comment]
Thanks for the notice, I fixed this in https://github.com/ethz-asl/kindr/pull/105
