### ISSUE TITLE
Why use private inheritance rather than composition?

### ISSUE THREAD

**Issue by furgalep** [ethz-asl/kindr#36]
This design seems strange to me:

https://github.com/ethz-asl/kindr/blob/master/include/kindr/poses/eigen/HomogeneousTransformation.hpp#L45-L46

The transformation is built with private inheritance rather than composition. What is the rationale behind this design choice?

**Comment by gehrinch** [comment]
We keep the inheritance in kindr 1.0.0 due to limited work force.
