### ISSUE TITLE
Why is there a differentiation between Pose and HomogeneousTransformation?

### ISSUE THREAD

**Issue by furgalep** [ethz-asl/kindr#37]
The documentation says:

> The class kindr::poses::PoseBase serves as an interface for a pose of a rigid body, i.e. the position and orientation of a rigid body. All types of representations of a pose, such as homogeneous transformations and screw motions, are derived from this base class.

I don't understand the distinction here...

**Comment by gehrinch** [comment]
This is simplified now in kindr 1.0.0.
