### ISSUE TITLE
NewKindr : Names ...

### ISSUE THREAD

**Issue by HannesSommer** [ethz-asl/kindr#51]
Let's try to find proper names for rotations to use it in the implementation of the core functionality of NewKindr:

We are seeking the name for the base class of all things that do rotate / or rotate and translate, purely having the purpose to specify the interface of something that rotates or rotates and translates, but without thinking of frames or any other modeling or physical related notion (to not have to interfere with different ways of thinking about aka active vs. passive). 

Candidates, I see right now:

 1. For pure rotations in 3d: 
   1. SO3,
   2. Rotation3 or Rot3, 
   3. ProperRotation3 or PRot3
 2. For pure translations in 3d: 
   1. T3
   2. Translation3 or Trans3, 
 3. For combinations of 1. and 2.
   1. SE3
   2. Isometry3 or Iso3
   3. Transformation3 or Trafo3
 
Please feel free to add some candidates.

I think we (or who is interested) also should discuss the naming for the primary action of these (yes we can have operators overloaded for them but we also could/should have names), which would be either specifically called like rotate or or more generically : apply, act, operate.

In some kind of correspondence to the interface names above, but that is only quite loosely coupled :

1. pure rotation:
  1. act, operate, apply
  2. rotate
  3. rotate
2. pure translations
  1. act, operate, apply
  2. translate
3. mixtures
  1. act, operate, apply
  2. act, operate, apply
  3. transform

As overloaded operators we have as candidates probably only:
1. operator ()
2. operator *

Why _translations_ (for those who like to know or to not have them there):
I would like to have them and would also implement them (almost no work), because from a conceptional point of view they they are just one third of the whole story about SE3. And they are crucial to conceptually well understand SE3 and the relation between SO3 and SE3 because 

SE3  = SO3 * T3 = T3 * SO3, 

where * is pairwise concatenation. 

Please don't oppose them just because you would not need them: they won't interfere! And no, they are not the same as vectors (Vec3). Vectors are the usual implementation for the translation, like the rotation matrix for a rotation / a SO3 element. And vectors are _also_ the things all those operations (rotation and translation and combinations of both) do _operate_ or _act_ upon! So for example a rotation does compose or concatenate with a translation (resulting in a mixture!) but acts or operates on a vector! So it is something different. Not properly understanding the difference is probably one important reason for a lot of confusion in that area. This essentially means that rotate would still get a Vec3 as argument and not a translation!

**Comment by gehrinch** [comment]
This is too much work for us. We keep it as it is for kindr version 1.0.0.
