### ISSUE TITLE
Missing file 'RotationEigen.hpp'

### ISSUE THREAD

**Issue by keyboardless** [ethz-asl/kindr#65]
I am trying to compile the project of ethz-asl/rovio which have dependency on this project.
Here is the error information that  indicate the 'RotationEigen.hpp' cannt be found.
I have installed kindr following the cmake install instructions. && I have noticed that 'RotationEigen.hpp' isnot in the code './include/' directory. Could anyone give me some instructions? thanks a lot ~!

* my environment : ubuntu 14.04 & ros version is indigo

> swordly@swordly-ThinkPad-T450:~/Work/vins/catkin_ws$ catkin build rovio --cmake-args -DCMAKE_BUILD_TYPE=Release -DMAKE_SCENE=ON
-----------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/indigo
Workspace:                   /home/swordly/Work/vins/catkin_ws
-----------------------------------------------------------------------
Source Space:       [exists] /home/swordly/Work/vins/catkin_ws/src
Log Space:          [exists] /home/swordly/Work/vins/catkin_ws/logs
Build Space:        [exists] /home/swordly/Work/vins/catkin_ws/build
Devel Space:        [exists] /home/swordly/Work/vins/catkin_ws/devel
Install Space:      [unused] /home/swordly/Work/vins/catkin_ws/install
DESTDIR:            [unused] None
-----------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-----------------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release -DMAKE_SCENE=ON
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-----------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-----------------------------------------------------------------------
Workspace configuration appears valid.
-----------------------------------------------------------------------
[build] Found '2' packages in 0.0 seconds.                                     
[build] Package table is up to date.                                           
Starting  >>> kindr                                                            
Finished  <<< kindr                [ 0.1 seconds ]                             
Starting  >>> rovio                                                            
_______________________________________________________________________________
Errors     << rovio:make /home/swordly/Work/vins/catkin_ws/logs/rovio/build.make.000.log
In file included from /home/swordly/Work/vins/catkin_ws/src/rovio/include/rovio/FeatureCoordinates.hpp:32:0,
                 from /home/swordly/Work/vins/catkin_ws/src/rovio/src/FeatureCoordinates.cpp:1:
/home/swordly/Work/vins/catkin_ws/src/rovio/lightweight_filtering/include/lightweight_filtering/common.hpp:13:45: fatal error: kindr/rotations/RotationEigen.hpp: No such file or directory
 #include "kindr/rotations/RotationEigen.hpp"
                                             ^
In file included from /home/swordly/Work/vins/catkin_ws/src/rovio/include/rovio/Camera.hpp:32:0,
                 from /home/swordly/Work/vins/catkin_ws/src/rovio/src/Camera.cpp:1:
/home/swordly/Work/vins/catkin_ws/src/rovio/lightweight_filtering/include/lightweight_filtering/common.hpp:13:45: fatal error: kindr/rotations/RotationEigen.hpp: No such file or directory
 #include "kindr/rotations/RotationEigen.hpp"
                                             ^
compilation terminated.
compilation terminated.
make[2]: *** [CMakeFiles/rovio.dir/src/FeatureCoordinates.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/rovio.dir/src/Camera.cpp.o] Error 1
In file included from /home/swordly/Work/vins/catkin_ws/src/rovio/include/rovio/Scene.hpp:32:0,
                 from /home/swordly/Work/vins/catkin_ws/src/rovio/src/Scene.cpp:1:
/home/swordly/Work/vins/catkin_ws/src/rovio/lightweight_filtering/include/lightweight_filtering/common.hpp:13:45: fatal error: kindr/rotations/RotationEigen.hpp: No such file or directory
 #include "kindr/rotations/RotationEigen.hpp"
                                             ^
compilation terminated.
make[2]: *** [CMakeFiles/rovio.dir/src/Scene.cpp.o] Error 1
In file included from /home/swordly/Work/vins/catkin_ws/src/rovio/include/rovio/RovioFilter.hpp:32:0,
                 from /home/swordly/Work/vins/catkin_ws/src/rovio/src/rovio_node.cpp:39:
/home/swordly/Work/vins/catkin_ws/src/rovio/lightweight_filtering/include/lightweight_filtering/common.hpp:13:45: fatal error: kindr/rotations/RotationEigen.hpp: No such file or directory
 #include "kindr/rotations/RotationEigen.hpp"
                                             ^
compilation terminated.
make[2]: *** [CMakeFiles/rovio.dir/src/rovio_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/rovio.dir/all] Error 2
make: *** [all] Error 2
cd /home/swordly/Work/vins/catkin_ws/build/rovio; catkin build --get-env rovio | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << rovio:make           [ Exited with code 2 ]                      
Failed    <<< rovio                [ 11.8 seconds ]                            
[build] Summary: 1 of 2 packages succeeded.                                    
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: None.                                                     
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 12.2 seconds total.

**Comment by gehrinch** [comment]
Rovio depends on the experimental version 0.0.1. Please checkout the tag 0.0.1.
